#debug=true
debug: false
#server.port=80
#前缀相同的配置项，idea会自动进行归纳
server:
 port: 8000
 servlet:
   context-path: /
 thymeleaf:
   cache: false
spring:
  mvc:
    date-format: yyyy-MM-dd
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root