#debug=true
debug: false
#server.port=80
#前缀相同的配置项，idea会自动进行归纳
server:
 port: 8000
 servlet:
   context-path: /
 thymeleaf:
   cache: false
spring:
  mvc:
    date-format: yyyy-MM-dd
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scott?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jackson:
    serialization:
      indent-output: true

#mybatis
#Core Config File
#start width /
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
#show sql
logging:
  level:
    com:
      example:
        sprintbootdemo:
          mapper: debug
